export default {
    tags: ['Moves'],
    description: "Place a move to a board from a game",
    operationId: 'postMove',
    requestBody: {
        content: {
            "application/json": {
                schema: {
                    type: 'object',
                    properties: {
                        gameId: {
                            type: 'string',
                            required: true,
                            description: 'ID from the game where the board belongs to.'
                        },
                        row: {
                            type: 'number',
                            required: true,
                            description: 'A row number (zero based) to move'
                        },
                        col: {
                            type: 'number',
                            required: true,
                            description: 'A col number (zero based) to move'
                        },
                        value: {
                            type: 'string',
                            description: 'A value to place in the square. Can be a F (flag mine) or a ? (doubt)'
                        },
                        showBoard: {
                            type: 'boolean',
                            description: 'Cheat. Retrieve the board generated by a move without mask.'
                        }
                    }
                }
            }
        }
    },
    responses: {
        "200": {
            description: "Move placed",
            content: {
                "application/json": {
                    schema: {
                        type: 'object',
                        properties: {
                            message: "string",
                            col: "number",
                            row: "number",
                            value: "string",
                            prettyBoard: "array",
                            cheatBoard: "array",
                            board: "array"
                        }
                    }
                }
            }
        }
    }
}